---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "Camera API"
  contact: {}
host: "camera"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /image:
    get:
      summary: "Get image."
      description: "Retrieve the current camera image."
      produces:
        - "image/jpeg"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            type: "string"
            format: "binary"
            description: "The current camera image."
  /settings:
    get:
      summary: "Get settings."
      description: "Retrieve a set of the exposed settings of the camera."
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            type: "array"
            description: "Set of the exposed settings of the camera."
            items:
              type: "string"
  /settings/{setting}:
    get:
      summary: "Get setting info."
      description: "Retrieve information about the specified setting."
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/Setting"
        404:
          description: "The specified setting is not available."
    parameters:
      - name: "setting"
        in: "path"
        required: true
        type: "string"
  /settings/{setting}/value:
    put:
      summary: "Set setting value."
      description: "Update the value of the specified setting.\nRefer to /settings/{setting}\
        \ for the valid values of the specified setting.\n"
      consumes: []
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/SettingValue"
      responses:
        204:
          description: "The setting value has been successfully updated."
        400:
          description: "The value of the setting cannot be edited or invalid value\
            \ provided."
        404:
          description: "The specified setting is not available."
    parameters:
      - name: "setting"
        in: "path"
        required: true
        type: "string"
definitions:
  Setting:
    type: "object"
    required:
      - "availableValues"
      - "editable"
      - "name"
      - "value"
    properties:
      name:
        type: "string"
      value:
        type: "string"
      editable:
        type: "boolean"
        description: "Specifies whether the value of the setting can be edited."
      availableValues:
        type: "array"
        items:
          type: "string"
  SettingValue:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: "string"
        description: "The setting value."